name: Multi-platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: win
          - platform: android32
          - platform: android64
          - platform: mac
          - platform: ios

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Geode
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk-version: 5.10.1

      - name: Build mod
        run: geode build -p ${{ matrix.platform }}
